apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-ui
    spec:
      containers:
      - name: weather-ui
        image: elnabatshy/weatherapp-ui:v1
        env:
        - name: AUTH_HOST
          value: "http://weatherapp-auth.default.svc.cluster.local:3000"
        - name: WEATHER_HOST
          value: "http://weatherapp-weather.default.svc.cluster.local:4000"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP